### ISSUE TITLE
colors per version

### ISSUE THREAD

**Issue by aronatkins** [mcanouil/quarto-version-badge#8]
Would it be possible to allow alternate colors to be provided for different named versions? For example, let's say that we have three versions of a product, alpha, beta, and gamma. I want to color the badges with orange, blue, and green. Other versions should be colored purple.

I don't know if this YAML structure fits with what you're thinking, but something along the lines of:

```yaml
version-badge:
    versions:
        - version: alpha
            color: orange
        - version: beta
            color: blue
        - version: gamma
            color: green
    defaults:
        color: purple
```

In the document, we could do something like:

```markdown
# some alpha-only feature {{< v alpha >}}

This is discussion about some very important feature that was introduced in the alpha release.
```

If a `color` keyword is too specific, perhaps the extension could support a `classes` enumeration that lets folks override the default `bg-success` and `bg-danger` choices.

Something like this idea would let folks configure additional colors without repeating the CSS style each time the shortcode is used.
