### ISSUE TITLE
links from shortcode

### ISSUE THREAD

**Issue by aronatkins** [mcanouil/quarto-version-badge#9]
Could the version-batch shortcode produce a link to a predeclared target? The current behavior (no link) would remain default, but perhaps specific named versions could receive a link.

Maybe this could be configured like the following, also allowing an optional default link:

```yaml
version-badge:
    versions:
        - version: alpha
            link: https://google.com/
        - version: beta
            link: https://posit.co/
    defaults:
        link: https://quarto.org/
```

Related to https://github.com/mcanouil/quarto-version-badge/issues/8
